// All action types
export const ADD_CATEGORIES = 'ADD_CATEGORIES'
export const SET_CURRENTCATEGORY = 'SET_CURRENTCATEGORY'
export const ADD_POSTS = 'ADD_POSTS'
export const ADD_POSTS_DETAILS = 'ADD_POSTS_DETAILS'
export const ADD_POSTS_COMMENTS = 'ADD_POSTS_COMMENTS'
export const EDIT_POSTS_DETAILS = 'EDIT_POSTS_DETAILS'
export const EDIT_POSTS_COMMENTS = 'EDIT_POSTS_COMMENTS'
export const ERROR = 'ERROR'
